# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jason Lambert
tagline:          'Développeur Web'
description:      'Développeur Web'
url:              jason-lambert.github.io

author:
  name:           'Jason Lambert'
  url:            https://jason-lambert.github.io

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Jason-Lambert/Jason-Lambert.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}